language: node_js

node_js:
  - "node"

addons:
  chrome: stable

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - greenkeeper-lockfile-update
  - npm run build

script:
  - npm test --runInBand --ci

after_script: greenkeeper-lockfile-upload

cache:
  directories:
    - "node_modules"
